[package]
name = "pure-be"
description = "HTTP API backend for a sudoku solver"
authors = ["17ms <hello@golfed.xyz>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
cpu-time = "1.0.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }

