name: Cargo CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo check --verbose                        # Dependencies
      - run: cargo build --verbose                        # Build
      - run: cargo clippy --verbose                       # Linting
      - run: cargo test --verbose -- --skip "test_sdfs"   # Tests (exclude the solver for now)

